version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    command: >
      bash -c "
        rabbitmq-server &
        sleep 10
        rabbitmqctl add_vhost test
        rabbitmqctl set_permissions -p test admin '.*' '.*' '.*'
        tail -f /dev/null
      "
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python producer.py
    volumes:
      - .:/app

  consumer:
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python consumer.py
    volumes:
      - .:/app